theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/E923A650-3719-45CB-8916-8078EA607D00.jpg
title: Mallory E. Gaspard
description: Applied Math Ph.D. Student and NDSEG Fellow at Cornell University
google_analytics: 

