theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/gaspard_cam_headshot.jpg
title: Mallory E. Gaspard
description: Applied Math Ph.D. Candidate at Cornell University
google_analytics: 

