theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/C63B3E14-BE7C-4BC8-9887-FC969FDD81C4.JPG
title: Mallory E. Gaspard
description: Applied Math Ph.D. Candidate at Cornell University
google_analytics: 

