theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/IMG_8307.jpeg
title: Mallory E. Gaspard
description: Applied Math Ph.D. Student at Cornell University
google_analytics: 
