theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/gaspard_cam_headshot.jpg
title: Mallory E. Gaspard
description: Postdoc at Princeton University
google_analytics: 

